# Generated by Django 5.1.6 on 2025-08-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='note',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
